name: Deploy to Orange Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Orange Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORANGE_PI_HOST }}
          username: ${{ secrets.ORANGE_PI_USERNAME }}
          key: ${{ secrets.ORANGE_PI_SSH_KEY }}
          script: |
            cd /home/orangepi/Sunsinev2
            ./update.sh 
            
